Repository containerish/openregistry-web, pull requests merged in 2022-04, with the labels that each got.

#29 Adhoc changes
  package.json
  src/apis/httpClient.ts
  src/components/pulse.svelte
  src/components/pulse.ts
  src/components/signin.svelte
  src/components/signup.svelte
  src/lib/errorModal.svelte
  src/lib/footer.svelte
  src/lib/navbar-auth.svelte
  src/lib/navbar-default.svelte
  src/lib/navbar.svelte
  src/lib/userStore.ts
  src/routes/__error.svelte
  src/routes/__layout.svelte
  src/routes/auth/[slug].svelte
  src/routes/home.svelte
  src/routes/index.svelte
  src/routes/repositories/index.svelte
  src/routes/search/index.svelte
  src/routes/settings/index.svelte
  src/routes/u/[username]/[repo].svelte
  src/routes/u/index.svelte
  src/stores/registry.ts
  src/stores/userStore.ts
  yarn.lock
Labels: bug, P2

#30 Fix: Modal on Search page
  src/routes/__error.svelte
  src/routes/__layout.svelte
  src/routes/search/index.svelte
Labels: bug, P3

#31 Fix: Repo list for user
  src/routes/repositories/index.svelte
Labels: bug

#35 Fix: joined today on settings page
  src/routes/settings/index.svelte
Labels: enhancement

#36 Fix: Container Pull Command
  src/routes/__layout.svelte
  src/routes/u/[username]/[repo].svelte
Labels: bug, enhancement, P3
